### ISSUE TITLE
BUG: plugin is not working in any way!

### ISSUE THREAD

**Issue by CptGummiball** [Maxlego08/zDrawer#2]
Server: Spigot 1.20.4
ZDrawer Version: 1.0.5
ZMenu Version: 1.0.2.7

Hi,
We installed the plugin yesterday and so far it doesn't work at all. An error occurs during a reload and drawers cannot be crafted or created via command. MySQL is set up and doesn't work either.

Apart from the database, we haven't changed anything else in the config.yml.

It would be very nice if this will be fixed soon or there is a solution for it.

Normally you can expect a plugin that costs $10 to work straight away.

**Comment by Maxlego08** [comment]
Hello, thank you for joining my discord for my help. Without information, log or your configuration it's impossible for me to help you 
[discord.groupez.dev](https://discord.groupez.dev)

**Comment by wolf128058** [comment]
co-admin here. i have a screenshot of the logfile for you:
![grafik](https://github.com/Maxlego08/zDrawer/assets/946255/b47d097b-1a20-4e26-b1ec-8e12db1ec211)

**Comment by Maxlego08** [comment]
Plz join my discord, to help you this will be simpler, because just screens like that I can’t do anything....

**Comment by CptGummiball** [comment]
Hello,
Since my co admin is having trouble contacting you and we're in a support loop here, I'll take a look at the code myself later. What I can definitely say is that the problem has to do directly with zDrawer and not with any other plugin that is interfering with the function.
I will give you an update as soon as I come to a conclusion.

**Comment by Maxlego08** [comment]
> Hello, Since my co admin is having trouble contacting you and we're in a support loop here, I'll take a look at the code myself later. What I can definitely say is that the problem has to do directly with zDrawer and not with any other plugin that is interfering with the function. I will give you an update as soon as I come to a conclusion.

Go on my discord and pinged me, https://discord.groupez.dev/  and if you don’t provide me with logs and information about your problems I couldn’t help you.

**Comment by wolf128058** [comment]
Joined your discord... beeing not allowed to write into the channel there.  😞
![grafik](https://github.com/Maxlego08/zDrawer/assets/946255/d2bf2549-cefa-4019-87cd-27911d862a3b)

**Comment by Maxlego08** [comment]
Open a ticket and send a proof of purchase :D

**Comment by CptGummiball** [comment]
Plugin is purchased by me, @wolf128058 is the main admin for the server by now until im back i will send you a proof via pm in discord

**Comment by CptGummiball** [comment]
Well i can't send you any PN. Here is the proof. I will also send it to @wolf128058 for the ticket if it is really needed
![Screenshot_2024-05-28-22-27-19-210-edit_com android chrome](https://github.com/Maxlego08/zDrawer/assets/151415484/579b8814-b5f8-46f2-8dc8-7dff44615406)

**Comment by wolf128058** [comment]
Logfile:

`[22:34:11] [Server thread/ERROR]: Error occurred while enabling zDrawer v1.0.7 (Is it up to date?)
java.lang.NoSuchMethodError: 'boolean org.bukkit.Server.removeRecipe(org.bukkit.NamespacedKey, boolean)'
        at fr.maxlego08.zdrawer.craft.ZCraft.unregister(ZCraft.java:86) ~[?:?]
        at fr.maxlego08.zdrawer.craft.ZCraft.register(ZCraft.java:68) ~[?:?]
        at fr.maxlego08.zdrawer.configuration.ZDrawerConfiguration.<init>(ZDrawerConfiguration.java:46) ~[?:?]
        at fr.maxlego08.zdrawer.ZDrawerManager.load(ZDrawerManager.java:94) ~[?:?]
        at fr.maxlego08.zdrawer.zcore.ZPlugin.lambda$loadFiles$0(ZPlugin.java:253) ~[?:?]
        at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
        at fr.maxlego08.zdrawer.zcore.ZPlugin.loadFiles(ZPlugin.java:253) ~[?:?]
        at fr.maxlego08.zdrawer.DrawerPlugin.onEnable(DrawerPlugin.java:64) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:539) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:3976-Spigot-06d602e-b3b43a6]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:453) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:3976-Spigot-06d602e-b3b43a6]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:623) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:3976-Spigot-06d602e-b3b43a6]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:409) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:3976-Spigot-06d602e-b3b43a6]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:250) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:3976-Spigot-06d602e-b3b43a6]
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1000) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:3976-Spigot-06d602e-b3b43a6]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:304) ~[spigot-1.20.4-R0.1-SNAPSHOT.jar:3976-Spigot-06d602e-b3b43a6]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
`

**Comment by Maxlego08** [comment]
what is your server ? spigot ? paper ?

**Comment by CptGummiball** [comment]
> Server: Spigot 1.20.4 ZDrawer Version: 1.0.5 ZMenu Version: 1.0.2.7
> 
> Hi, We installed the plugin yesterday and so far it doesn't work at all. An error occurs during a reload and drawers cannot be crafted or created via command. MySQL is set up and doesn't work either.
> 
> Apart from the database, we haven't changed anything else in the config.yml.
> 
> It would be very nice if this will be fixed soon or there is a solution for it.
> 
> Normally you can expect a plugin that costs $10 to work straight away.

**We've already updates it more than one time since the ticket was opened, nothing works**

**Comment by wolf128058** [comment]
zMenu is updated to 1.0.3.1

**Comment by CptGummiball** [comment]
Since no solution has been provided, we have decided to abandon the idea of using this plugin.

The support has been disappointing; we've been repeatedly redirected without receiving any concrete answers.

The plugin doesn't work at all with Spigot, which might explain why, according to the statistics, it appears to be hardly used with Spigot.
